// Data extracted verbatim from the Figma Make export (src/app/App.tsx)

const TEAM_AND_FELLOWS = [
  { name: "Jennie Glazer", title: "Chief Executive Officer" },
  { name: "Bailey Anderson", title: "Intern, The Global Lab" },
  { name: "Mia Banner", title: "Vice President, Strategic Partnerships" },
  { name: "Jennifer Brown", title: "Founding Luminary\nCTI Luminary Exchange" },
  { name: "Andy Chan", title: "Senior Manager of Data & Analysis at the Global Lab" },
  { name: "Danielle Cruz", title: "Vice President of People & Experience" },
  { name: "Radhika Darbari", title: "Fellow at Coqual's Global Lab & Senior Advisor, Asia" },
  { name: "Isis Fabian", title: "Executive-in-Residence at Coqual's Global Lab" },
  { name: "Jeyandini Fernando", title: "Senior Director, Client Experience & Communications" },
  { name: "Emily Gawlak", title: "Co-Executive Director of Coqual's Global Lab" },
  { name: "Melissa Ng Goldner", title: "Executive in Residence, Head of Strategy & Research" },
  { name: "Abenaa Hayes", title: "Fellow at Coqual's Global Lab, Founder, Elysée Consulting" },
  { name: "Melinda Marshall", title: "Fellow at Coqual's Global Lab" },
  { name: "Birgit Neu", title: "Fellow at Coqual's Global Lab & Senior Advisor, UK/Europe" },
  { name: "Sandra Rice", title: "Executive Vice President, Corporate Strategy & Engagement" },
  { name: "Peggy Shiller", title: "Chief Administrative Officer" },
  { name: "Tiffany Tay", title: "Fellow at Coqual's Global Lab" },
  { name: "Allegra Varnadore", title: "Vice President, Corporate Strategy & Engagement" },
  { name: "Elana J. Weinstein", title: "Fellow at Coqual's Global Lab" },
  { name: "Emilia Yu", title: "Co-Executive Director of Coqual's Global Lab" },
  { name: "Eunice Yu", title: "Senior Vice President of the Global Lab" },
];

const BOARD = [
  { name: "Carolyn Buck Luce", title: "Co-founder & Chairman of the Board · Co-founder & Managing Partner, Imaginal Labs" },
  { name: "Laura Posadas", title: "Treasurer · President & CEO, Canlak Coatings" },
  { name: "Karen Bernhard", title: "Data Executive" },
  { name: "Patricia Fili-Krushel", title: "Former Chairman of the Board" },
  { name: "Trevor Gandy", title: "Global Head of I&D, AXA XL" },
  { name: "Kent A. Gardiner", title: "Partner & Former Chairman, Crowell & Moring LLP" },
  { name: "Jennie Glazer", title: "Chief Executive Officer, CTI" },
  { name: "Kellie A. McElhaney", title: "Founder & Executive Director, Center for Equity, Gender and Leadership" },
  { name: "Ellen McGirt", title: "Award-Winning Business Journalist & Community Builder" },
  { name: "Susan Reid", title: "Global Head of Talent, Morgan Stanley" },
  { name: "David G. Richardson", title: "Partner, Reitler Kailas & Rosenblatt LLP" },
  { name: "Melinda B. Wolfe", title: "Former Chief People Officer / HR Consultant / Executive Coach" },
];

const FORUM_EVENTS = [
  // ── 2027 Premium Events ────────────────────────────────────────────────────
  {
    id: "jan-2027", title: "Premium Member Orientation and Strategy Intake",
    format: "Member Briefing",
    month: "JAN", day: "27", date: "Jan 27, 2027",
    timeNYC: "11:00 AM ET", timeLondon: "4:00 PM GMT", timeGermany: "5:00 PM CET", timeMumbai: "9:30 PM IST",
    location: "Virtual", tag: "Member Hub", topic: "Talent & Performance", geography: ["Global"], access: "Premium", membersOnly: true, past: false,
    audience: "Member leads, HR, talent, inclusion, learning, workforce leads",
    description: "Help members plan how to use CTI based on their priorities. This session maps your organization's talent and inclusion challenges to the full CTI resource set for 2027.",
    pillar: "Member Hub / The Forum",
    speakers: [{ name: "CTI Member Success Lead", role: "Facilitator, TBD" }, { name: "Senior CTI Advisor", role: "Strategic Planning, TBD" }],
  },
  {
    id: "feb-2027", title: "Performance Systems and Neuroinclusion",
    format: "Coqual Global Lab Briefing",
    month: "FEB", day: "10", date: "Feb 10, 2027",
    timeNYC: "11:00 AM ET", timeLondon: "4:00 PM GMT", timeGermany: "5:00 PM CET", timeMumbai: "9:30 PM IST",
    location: "Virtual", tag: "Organizational Performance", topic: "Talent & Performance", geography: ["Global"], access: "Premium", membersOnly: true, past: false,
    audience: "Talent, performance, learning, HR, managers",
    description: "Share research on how feedback, evaluation, advancement, and work style can misread contribution. New Coqual Global Lab findings on neuroinclusive performance systems.",
    pillar: "Coqual Global Lab",
    speakers: [{ name: "Coqual Global Lab Researcher", role: "Lead Presenter, TBD" }, { name: "Luminary Speaker", role: "Neuroinclusion Practice, TBD" }],
  },
  {
    id: "mar-2027", title: "Women, Sponsorship, and the Next Era of Talent",
    format: "CTI Signature Session",
    month: "MAR", day: "16", date: "Mar 16, 2027",
    timeNYC: "11:00 AM ET", timeLondon: "3:00 PM GMT", timeGermany: "4:00 PM CET", timeMumbai: "8:30 PM IST",
    location: "Virtual", tag: "Talent Strategy", topic: "Talent & Performance", geography: ["Global"], access: "Premium", membersOnly: true, past: false,
    audience: "Employees, managers, sponsors, ERG/BRG leaders, emerging leaders",
    description: "Broad internal session for International Women's Day / Women's History Month focused on sponsorship, advocacy, and advancement. Designed for company-wide deployment.",
    pillar: "The Forum / CTILearning",
    speakers: [{ name: "Jennifer Brown", role: "Founding Luminary, CTI" }, { name: "CTI Forum Facilitator", role: "Session Lead, TBD" }],
  },
  {
    id: "apr-2027", title: "The Futurist's Guide to Work Redesign",
    format: "The Forum Salon",
    month: "APR", day: "21", date: "Apr 21, 2027",
    timeNYC: "11:00 AM ET", timeLondon: "4:00 PM BST", timeGermany: "5:00 PM CEST", timeMumbai: "8:30 PM IST",
    location: "Virtual", tag: "Future of Work", topic: "Future of Work", geography: ["Global"], access: "Premium", membersOnly: true, past: false,
    audience: "HR transformation, workforce strategy, talent, learning, business leaders",
    description: "Peer room on roles, teams, skills, career paths, judgment, and trust as work is redesigned. Structured practitioner exchange — not a presentation.",
    pillar: "The Forum",
    speakers: [{ name: "Charlene Li", role: "Luminary · Futurist, Quantum Networks Group" }, { name: "Tony Bynum", role: "Luminary · ID at Illinois Tech" }],
  },
  {
    id: "may-2027", title: "Reimagining the First Rung of Work",
    format: "Member Design Lab",
    month: "MAY", day: "12", date: "May 12, 2027",
    timeNYC: "11:00 AM ET", timeLondon: "4:00 PM BST", timeGermany: "5:00 PM CEST", timeMumbai: "8:30 PM IST",
    location: "Virtual", tag: "AI + Work", topic: "AI & Workforce", geography: ["Global"], access: "Premium", membersOnly: true, past: false,
    audience: "Talent, workforce innovation, early-career, learning, HR transformation",
    description: "Working session on entry-level work, pathways, early talent, and how people build experience when AI handles formative tasks. Members bring real design challenges.",
    pillar: "The Forum",
    speakers: [{ name: "Kate Devlin, Ph.D.", role: "Luminary · King's College London" }, { name: "CTI Lab Researcher", role: "Early Career Research Lead, TBD" }],
  },
  {
    id: "jun-2027", title: "Belonging, Employee Communities, and the Work of Connection",
    format: "CTI Signature Session",
    month: "JUN", day: "9", date: "Jun 9, 2027",
    timeNYC: "11:00 AM ET", timeLondon: "4:00 PM BST", timeGermany: "5:00 PM CEST", timeMumbai: "8:30 PM IST",
    location: "Virtual", tag: "DEI Evolution", topic: "Organizational Culture & Trust", geography: ["Global"], access: "Premium", membersOnly: true, past: false,
    audience: "Employees, managers, ERG/BRG leaders, sponsors, inclusion leads",
    description: "Broad internal session for Pride / belonging / employee communities. Designed for company-wide deployment during Pride Month and employee community programming.",
    pillar: "The Forum / CTILearning",
    speakers: [{ name: "Trey Boynton", role: "Luminary · Chief, Chief D&PO" }, { name: "Rev. Mark Fowlder", role: "Luminary · Tanenbaum Center" }],
  },
  {
    id: "jul-2027", title: "Strategy 2028",
    format: "Strategy Briefing / Working Session",
    month: "JUL", day: "14", date: "Jul 14, 2027",
    timeNYC: "11:00 AM ET", timeLondon: "4:00 PM BST", timeGermany: "5:00 PM CEST", timeMumbai: "8:30 PM IST",
    location: "Virtual", tag: "Future of Work", topic: "Future of Work", geography: ["Global"], access: "Premium", membersOnly: true, past: false,
    audience: "Senior leaders, HR, talent, inclusion, workforce leads",
    description: "Help members look ahead before 2028 priorities harden. CTI shares emerging signals, research in progress, and a structured forward-planning framework for member organizations.",
    pillar: "The Forum",
    speakers: [{ name: "Jennifer D. Sciubba, Ph.D.", role: "Luminary · Population Reference Bureau" }, { name: "CTI Research Director", role: "2028 Signal Report, TBD" }],
  },
  {
    id: "aug-2027", title: "What Are We Missing?",
    format: "Insight to Action",
    month: "AUG", day: "11", date: "Aug 11, 2027",
    timeNYC: "11:00 AM ET", timeLondon: "4:00 PM BST", timeGermany: "5:00 PM CEST", timeMumbai: "8:30 PM IST",
    location: "Virtual", tag: "Organizational Performance", topic: "Talent & Performance", geography: ["Global"], access: "Premium", membersOnly: true, past: false,
    audience: "HR, talent, inclusion, learning, employee experience, workforce leads",
    description: "Help members compare perspectives, pressure-test assumptions, and identify what to try, rethink, or stop. Structured reflection session using CTI Playbooks framework.",
    pillar: "The Forum / CTI Playbooks",
    speakers: [{ name: "Anna Tavis, Ph.D.", role: "Luminary · NYU Human Capital Management" }, { name: "CTI Forum Facilitator", role: "Session Lead, TBD" }],
  },
  {
    id: "sep-2027", title: "Talent Leader's Guide to Scaling Convergent Leadership",
    format: "Coqual Global Lab Briefing",
    month: "SEP", day: "15", date: "Sep 15, 2027",
    timeNYC: "11:00 AM ET", timeLondon: "4:00 PM BST", timeGermany: "5:00 PM CEST", timeMumbai: "8:30 PM IST",
    location: "Virtual", tag: "Leadership + Culture", topic: "Leadership", geography: ["Global"], access: "Premium", membersOnly: true, past: false,
    audience: "Talent leaders, leadership development, managers, HR transformation",
    description: "Help talent leaders build capability that shows up in decisions, not just competency models. New Global Lab findings on convergent leadership and practical scaling frameworks.",
    pillar: "Coqual Global Lab / CTILearning",
    speakers: [{ name: "Tomas Chamorro-Premuzic, Ph.D.", role: "Luminary · Russell Reynolds Associates" }, { name: "CTI Lab Researcher", role: "Leadership Research Lead, TBD" }],
  },
  {
    id: "oct-2027", title: "Work Style, Feedback, and Neuroinclusive Performance",
    format: "CTI Signature Session",
    month: "OCT", day: "27", date: "Oct 27, 2027",
    timeNYC: "11:00 AM ET", timeLondon: "4:00 PM GMT", timeGermany: "5:00 PM CET", timeMumbai: "9:30 PM IST",
    location: "Virtual", tag: "Organizational Performance", topic: "Talent & Performance", geography: ["Global"], access: "Premium", membersOnly: true, past: false,
    audience: "Employees, managers, talent, performance, learning, HR",
    description: "Broad internal session for Disability Employment Awareness Month focused on managers, feedback, and work style. Designed for company-wide deployment in October.",
    pillar: "The Forum / Coqual Global Lab",
    speakers: [{ name: "CTI Lab Researcher", role: "Neuroinclusion Research, TBD" }, { name: "CTI Forum Facilitator", role: "Session Lead, TBD" }],
  },
  {
    id: "nov-2027", title: "What Should the Business Own?",
    format: "The Forum Salon",
    month: "NOV", day: "17", date: "Nov 17, 2027",
    timeNYC: "11:00 AM ET", timeLondon: "4:00 PM GMT", timeGermany: "5:00 PM CET", timeMumbai: "9:30 PM IST",
    location: "Virtual", tag: "Workforce Design", topic: "Future of Work", geography: ["Global"], access: "Premium", membersOnly: true, past: false,
    audience: "Senior leaders, HR, talent, inclusion, business leaders",
    description: "Help members decide what central teams should own, what the business should own, and what should stop, shift, or scale. Practitioner peer room.",
    pillar: "The Forum",
    speakers: [{ name: "Alison Taylor", role: "Luminary · NYU Stern School of Business" }, { name: "CTI Forum Facilitator", role: "Session Lead, TBD" }],
  },
  {
    id: "dec-2027", title: "Coqual Summit 2026: Community of Consequence",
    format: "Flagship Convening",
    month: "DEC", day: "4", date: "Dec 4, 2026",
    timeNYC: "9:00 AM ET", timeLondon: "2:00 PM GMT", timeGermany: "3:00 PM CET", timeMumbai: "7:30 PM IST",
    location: "New York City + Virtual", tag: "Summit", topic: "Leadership", geography: ["United States", "Global"], access: "Premium + Co-Chair", membersOnly: true, past: false,
    audience: "Members, senior leaders, researchers, Luminaries, member organizations",
    description: "For one day in New York City and virtually, Coqual brings together 200+ senior leaders, members, business operators, academics, cultural thinkers, and issue experts shaping the future of work in real time — candid, high-trust, and practical.",
    pillar: "The Forum / CTI Summit",
    speakers: [{ name: "Jennie Glazer", role: "CEO, Coqual" }, { name: "William Ury", role: "Author, Possible; Co-founder, Program on Negotiation, Harvard University" }, { name: "Nikole Hannah-Jones", role: "Pulitzer Prize-winning Reporter, Founder, 1619 Project" }],
  },
  // ── 2027 Co-Chair Events ───────────────────────────────────────────────────
  {
    id: "cochair-feb-2027", title: "Co-Chair Strategy Intake",
    format: "Co-Chair Session",
    month: "FEB", day: "24", date: "Feb 24, 2027",
    timeNYC: "11:00 AM ET", timeLondon: "4:00 PM GMT", timeGermany: "5:00 PM CET", timeMumbai: "9:30 PM IST",
    location: "Virtual", tag: "Co-Chair", topic: "Talent & Performance", geography: ["Global"], access: "Co-Chair", membersOnly: true, past: false,
    audience: "Co-Chair member lead, CTI leadership, senior sponsor",
    description: "Align CTI to the member's priorities and identify likely First Call topics. Output: Co-Chair Use Plan.",
    pillar: "Co-Chair Advisory",
    speakers: [{ name: "CTI Co-Chair Lead", role: "Facilitator, TBD" }],
  },
  {
    id: "cochair-may-2027", title: "Co-Chair Agenda Council 1",
    format: "Co-Chair Session",
    month: "MAY", day: "5", date: "May 5, 2027",
    timeNYC: "11:00 AM ET", timeLondon: "4:00 PM BST", timeGermany: "5:00 PM CEST", timeMumbai: "8:30 PM IST",
    location: "Virtual", tag: "Co-Chair", topic: "Talent & Performance", geography: ["Global"], access: "Co-Chair", membersOnly: true, past: false,
    audience: "Co-Chair members, CTI leadership",
    description: "Shape research questions, Forum topics, and emerging member needs. Output: Co-Chair Agenda Memo.",
    pillar: "Agenda-Shaping Access",
    speakers: [{ name: "CTI Research Director", role: "Agenda Lead, TBD" }],
  },
  {
    id: "cochair-jul-2027", title: "Strategy 2028 Co-Chair Roundtable",
    format: "Co-Chair Session",
    month: "JUL", day: "21", date: "Jul 21, 2027",
    timeNYC: "11:00 AM ET", timeLondon: "4:00 PM BST", timeGermany: "5:00 PM CEST", timeMumbai: "8:30 PM IST",
    location: "Virtual", tag: "Co-Chair", topic: "Talent & Performance", geography: ["Global"], access: "Co-Chair", membersOnly: true, past: false,
    audience: "Co-Chair members, CTI leadership",
    description: "Help CTI identify what members should be preparing for next. Output: Strategy 2028 Co-Chair Addendum.",
    pillar: "Agenda-Shaping Access",
    speakers: [{ name: "CTI Co-Chair Lead", role: "Facilitator, TBD" }],
  },
  {
    id: "cochair-nov-2027", title: "Co-Chair Agenda Council 2",
    format: "Co-Chair Session",
    month: "NOV", day: "3", date: "Nov 3, 2027",
    timeNYC: "11:00 AM ET", timeLondon: "3:00 PM GMT", timeGermany: "4:00 PM CET", timeMumbai: "8:30 PM IST",
    location: "Virtual", tag: "Co-Chair", topic: "Talent & Performance", geography: ["Global"], access: "Co-Chair", membersOnly: true, past: false,
    audience: "Co-Chair members, CTI leadership",
    description: "Shape Summit questions and 2028 research / convening priorities. Output: 2028 Agenda Preview.",
    pillar: "Agenda-Shaping Access",
    speakers: [{ name: "CTI Research Director", role: "Agenda Lead, TBD" }],
  },
];

const LAB_REPORTS = [
  // ── Most recent (always public) ─────────────────────────────
  { type: "Research Report", resourceType: "Research Report", title: "The Convergent Leader", date: "Feb 2026", tag: "Leadership + Culture", topic: "Leadership", issues: "Innovation", market: "France, Germany, U.K.", geography: ["France", "Germany", "United Kingdom"], identities: "Generations, Women", gated: false, series: null },
  { type: "Research Report", resourceType: "Research Report", title: "Pride Under Pressure", date: "Mar 2025", tag: "DEI Evolution", topic: "Organizational Culture & Trust", issues: "Belonging, Bias, Equity, Intersectionality, LGBTQ+, Representation", market: "Brazil, India, South Africa, U.K., U.S.", geography: ["Brazil", "India", "South Africa", "United Kingdom", "United States"], identities: "LGBTQ", gated: true, series: null },
  { type: "Research Report", resourceType: "Research Report", title: "The Neuroinclusion Imperative", date: "Oct 2025", tag: "Organizational Performance", topic: "Talent & Performance", issues: "Neuroinclusion, Performance, Feedback, Work Style", market: "Global", geography: ["Global"], identities: "Neurodivergent Employees", gated: false, series: null },
  // ── Belonging Studies (public) ───────────────────────────────
  { type: "Research Report", resourceType: "Research Report", title: "More than a Monolith", date: "Apr 2024", tag: "DEI Evolution", topic: "Organizational Culture & Trust", issues: "", market: "", geography: [], identities: "", gated: true, series: null },
  { type: "Research Report", resourceType: "Research Report", title: "Strangers at Home", date: "Jan 2023", tag: "DEI Evolution", topic: "Organizational Culture & Trust", issues: "Belonging, Bias, Equity, Politics, Race, Representation", market: "U.S.", geography: ["United States"], identities: "Asian/Asian Americans, Asians", gated: true, series: null },
  { type: "Research Report", resourceType: "Research Report", title: "Equity Calls on Everyone", date: "Nov 2021", tag: "DEI Evolution", topic: "Organizational Culture & Trust", issues: "Belonging, Equity, Intersectionality, Representation", market: "U.S.", geography: ["United States"], identities: "Asians, Black Talent, Ethnicity, Latinx, LGBTQ, White Men, Women", gated: true, series: null },
  { type: "Research Report", resourceType: "Research Report", title: "Equity at Work", date: "Oct 2021", tag: "DEI Evolution", topic: "Organizational Culture & Trust", issues: "Belonging, Equity, Innovation, Representation", market: "U.S.", geography: ["United States"], identities: "Asians, Black Talent, Ethnicity, Latinx, Millennials, White Men, Women", gated: true, series: null },
  // ── Belonging Series (public — reports with "Belonging" in title) ───────────
  { type: "Research Report", resourceType: "Research Report", title: "Belonging Matters Everywhere", date: "Dec 2020", tag: "DEI Evolution", topic: "Organizational Culture & Trust", issues: "Belonging, Bias, Politics, Recession", market: "China, India, Mexico", geography: ["China", "India", "Mexico"], identities: "Asians, LGBTQ, Women", gated: false, series: "Belonging" },
  { type: "Research Report", resourceType: "Research Report", title: "Belonging Matters Everywhere (U.K. & Germany)", date: "Dec 2020", tag: "DEI Evolution", topic: "Organizational Culture & Trust", issues: "Belonging", market: "Germany, U.K.", geography: ["Germany", "United Kingdom"], identities: "Asians, LGBTQ, Women", gated: false, series: "Belonging" },
  { type: "Research Report", resourceType: "Research Report", title: "The Power of Belonging", date: "Sep 2020", tag: "DEI Evolution", topic: "Organizational Culture & Trust", issues: "Advancement, Belonging, Intersectionality, Politics, Race, Representation", market: "U.S.", geography: ["United States"], identities: "Asians, Black Talent", gated: false, series: "Belonging" },
  // ── Sponsorship Series (public — reports with "Sponsor" in title) ──────────
  { type: "Research Report", resourceType: "Research Report", title: "Challenging Norms", date: "Jul 2023", tag: "Talent Strategy", topic: "Talent & Performance", issues: "Advancement, Equity, Intersectionality, Pay Gap, Race, Representation, Sponsorship", market: "Australia, Brazil, Germany, India, Japan, South Africa, U.K., U.S.", geography: ["Australia", "Brazil", "Germany", "India", "Japan", "South Africa", "United Kingdom", "United States"], identities: "Asians, Baby Boomers, Generation X, Latinx, LGBTQ, Millennials, White Men, Women", gated: true, series: null },
  { type: "Research Report", resourceType: "Research Report", title: "The Sponsor Dividend", date: "Sep 2020", tag: "Talent Strategy", topic: "Talent & Performance", issues: "Advancement, Race, Representation, Sponsorship, Talent Retention", market: "U.S.", geography: ["United States"], identities: "Generation X, Generations, Millennials", gated: false, series: "Sponsorship" },
  { type: "Research Report", resourceType: "Research Report", title: "Sponsor Effect 2.0", date: "Sep 2020", tag: "Talent Strategy", topic: "Talent & Performance", issues: "Advancement, Representation, Sponsorship, Talent Retention", market: "U.S.", geography: ["United States"], identities: "Baby Boomers, Ethnicity, Generation X, Millennials", gated: false, series: "Sponsorship" },
  { type: "Research Report", resourceType: "Research Report", title: "Sponsor Effect (Canada)", date: "Sep 2020", tag: "Talent Strategy", topic: "Talent & Performance", issues: "Advancement, Intersectionality, Representation, Sponsorship", market: "Canada", geography: ["Canada"], identities: "Baby Boomers, Ethnicity, Generation X, Millennials", gated: false, series: "Sponsorship" },
  { type: "Research Report", resourceType: "Research Report", title: "Sponsor Effect (U.K.)", date: "Sep 2020", tag: "Talent Strategy", topic: "Talent & Performance", issues: "Representation, Sponsorship", market: "U.K.", geography: ["United Kingdom"], identities: "Generations", gated: false, series: "Sponsorship" },
  { type: "Research Report", resourceType: "Research Report", title: "Forget a Mentor, Find a Sponsor", date: "Sep 2020", tag: "Talent Strategy", topic: "Talent & Performance", issues: "Advancement, Representation, Sponsorship, Talent Retention", market: "U.S.", geography: ["United States"], identities: "Baby Boomers, Generation X, Generations, Millennials", gated: false, series: "Sponsorship" },
  // ── Members only ─────────────────────────────────────────────
  { type: "Research Report", resourceType: "Research Report", title: "Being Black in the United Kingdom", date: "2022", tag: "DEI Evolution", topic: "Organizational Culture & Trust", issues: "Belonging, Equity, Race, Representation", market: "U.K.", geography: ["United Kingdom"], identities: "Black Talent", gated: true, series: null },
  { type: "Research Report", resourceType: "Research Report", title: "Equity and Ethnicity at Work", date: "Feb 2022", tag: "DEI Evolution", topic: "Organizational Culture & Trust", issues: "Equity, Race, Representation", market: "Brazil, Canada, China, Germany, India, South Africa, Turkey, U.K., U.S.", geography: ["Brazil", "Canada", "China", "Germany", "India", "South Africa", "Turkey", "United Kingdom", "United States"], identities: "Ethnicity", gated: true, series: null },
  { type: "Research Report", resourceType: "Research Report", title: "What Majority Men Really Think About D&I", date: "Sep 2020", tag: "DEI Evolution", topic: "Organizational Culture & Trust", issues: "Advancement, Belonging, Politics, Race", market: "U.S.", geography: ["United States"], identities: "Majority Men, White Men", gated: true, series: null },
  { type: "Research Report", resourceType: "Research Report", title: "Being Black in Corporate America", date: "Sep 2020", tag: "DEI Evolution", topic: "Organizational Culture & Trust", issues: "Advancement, Bias, Courageous Conversations, Entrepreneurship, Equity, Intersectionality, Race", market: "U.S.", geography: ["United States"], identities: "Black Talent", gated: true, series: null },
  { type: "Research Report", resourceType: "Research Report", title: "What #MeToo Means for Corporate America", date: "Sep 2020", tag: "DEI Evolution", topic: "Organizational Culture & Trust", issues: "#MeToo, Bias, Equity, Intersectionality", market: "U.S.", geography: ["United States"], identities: "Ethnicity, Women", gated: true, series: null },
  { type: "Research Report", resourceType: "Research Report", title: "Wonder Women in STEM", date: "Sep 2020", tag: "Talent Strategy", topic: "Talent & Performance", issues: "Advancement, Bias, Equity, Pay Gap, Representation, Women and STEM", market: "U.S.", geography: ["United States"], identities: "Women", gated: true, series: null },
  { type: "Research Report", resourceType: "Research Report", title: "Easing Racial Tensions at Work", date: "Sep 2020", tag: "DEI Evolution", topic: "Organizational Culture & Trust", issues: "Bias, Courageous Conversations, Equity, Race", market: "U.S.", geography: ["United States"], identities: "Asians, Black Talent, Ethnicity, Latinx", gated: true, series: null },
  { type: "Research Report", resourceType: "Research Report", title: "Disabilities and Inclusion", date: "Sep 2020", tag: "DEI Evolution", topic: "Organizational Culture & Trust", issues: "Bias, Equity, Intersectionality, Representation", market: "Brazil, Germany, India, Japan, U.K.", geography: ["Brazil", "Germany", "India", "Japan", "United Kingdom"], identities: "Disabilities", gated: true, series: null },
  { type: "Research Report", resourceType: "Research Report", title: "Disrupt Bias, Drive Value", date: "Sep 2020", tag: "DEI Evolution", topic: "Organizational Culture & Trust", issues: "Bias, Equity", market: "U.S.", geography: ["United States"], identities: "", gated: true, series: null },
  { type: "Research Report", resourceType: "Research Report", title: "Out in the World", date: "Sep 2020", tag: "DEI Evolution", topic: "Organizational Culture & Trust", issues: "Bias, Courageous Conversations, Equity, Intersectionality, Representation", market: "Brazil, China, Hong Kong, India, Russia, Singapore, South Africa, Turkey, U.K., U.S.", geography: ["Brazil", "China", "Hong Kong", "India", "Russia", "Singapore", "South Africa", "Turkey", "United Kingdom", "United States"], identities: "LGBTQ", gated: true, series: null },
  { type: "Research Report", resourceType: "Research Report", title: "Latinos at Work", date: "Sep 2020", tag: "DEI Evolution", topic: "Organizational Culture & Trust", issues: "Bias, Courageous Conversations, Equity, Intersectionality, Representation", market: "U.S.", geography: ["United States"], identities: "Ethnicity, Latinx", gated: true, series: null },
  { type: "Research Report", resourceType: "Research Report", title: "Mission Critical", date: "Sep 2020", tag: "Talent Strategy", topic: "Talent & Performance", issues: "Advancement", market: "U.S.", geography: ["United States"], identities: "Veterans", gated: true, series: null },
  { type: "Research Report", resourceType: "Research Report", title: "Reimagining Healthcare", date: "Sep 2020", tag: "Talent Strategy", topic: "Talent & Performance", issues: "Equity", market: "Brazil, Germany, Japan, U.K., U.S.", geography: ["Brazil", "Germany", "Japan", "United Kingdom", "United States"], identities: "Women", gated: true, series: null },
  { type: "Research Report", resourceType: "Research Report", title: "Ambition in Black & White", date: "Sep 2020", tag: "DEI Evolution", topic: "Organizational Culture & Trust", issues: "Courageous Conversations, Equity, Intersectionality, Race, Representation", market: "U.S.", geography: ["United States"], identities: "Black Talent, Women", gated: true, series: null },
  { type: "Research Report", resourceType: "Research Report", title: "Misunderstood Millennial Talent", date: "Sep 2020", tag: "Talent Strategy", topic: "Talent & Performance", issues: "Advancement, Belonging, Bias, Sponsorship", market: "U.S.", geography: ["United States"], identities: "Generations, Millennials", gated: true, series: null },
  { type: "Research Report", resourceType: "Research Report", title: "Harnessing the Power of the Purse", date: "Sep 2020", tag: "Talent Strategy", topic: "Talent & Performance", issues: "Advancement, Entrepreneurship, Intersectionality", market: "China, Hong Kong, India, Singapore, U.K., U.S.", geography: ["China", "Hong Kong", "India", "Singapore", "United Kingdom", "United States"], identities: "Women", gated: true, series: null },
  { type: "Research Report", resourceType: "Research Report", title: "Black Women Ready to Lead", date: "Sep 2020", tag: "DEI Evolution", topic: "Organizational Culture & Trust", issues: "Bias, Courageous Conversations, Equity, Intersectionality, Race, Representation", market: "U.S.", geography: ["United States"], identities: "Black Talent, Women", gated: true, series: null },
  { type: "Research Report", resourceType: "Research Report", title: "The Power of the Purse", date: "Sep 2020", tag: "Talent Strategy", topic: "Talent & Performance", issues: "Advancement, Belonging, Equity, Pay Gap, Talent Retention", market: "Brazil, Germany, Japan, U.K., U.S.", geography: ["Brazil", "Germany", "Japan", "United Kingdom", "United States"], identities: "Women", gated: true, series: null },
  { type: "Research Report", resourceType: "Research Report", title: "Growing Global Executives", date: "Sep 2020", tag: "Leadership + Culture", topic: "Leadership", issues: "Advancement, Belonging, Courageous Conversations, Equity, Innovation, Intersectionality", market: "Brazil, China, Hong Kong, India, Japan, Russia, Singapore, South Africa, Turkey, U.K., U.S.", geography: ["Brazil", "China", "Hong Kong", "India", "Japan", "Russia", "Singapore", "South Africa", "Turkey", "United Kingdom", "United States"], identities: "", gated: true, series: null },
  { type: "Research Report", resourceType: "Research Report", title: "How Diversity Drives Innovation", date: "Sep 2020", tag: "DEI Evolution", topic: "Organizational Culture & Trust", issues: "#MeToo, Belonging, Equity, Talent Retention", market: "U.S.", geography: ["United States"], identities: "Ethnicity, Generations", gated: true, series: null },
  { type: "Research Report", resourceType: "Research Report", title: "Athena Factor 2.0", date: "Sep 2020", tag: "Talent Strategy", topic: "Talent & Performance", issues: "Advancement, Intersectionality, Women and STEM", market: "Brazil, China, India, U.S.", geography: ["Brazil", "China", "India", "United States"], identities: "Women", gated: true, series: null },
  { type: "Research Report", resourceType: "Research Report", title: "Executive Presence", date: "Sep 2020", tag: "Leadership + Culture", topic: "Leadership", issues: "Bias, Race, Representation", market: "U.S.", geography: ["United States"], identities: "", gated: true, series: null },
  { type: "Research Report", resourceType: "Research Report", title: "Women Want Five Things", date: "Sep 2020", tag: "Talent Strategy", topic: "Talent & Performance", issues: "Equity, Intersectionality", market: "Germany, U.K., U.S.", geography: ["Germany", "United Kingdom", "United States"], identities: "Women", gated: true, series: null },
  { type: "Research Report", resourceType: "Research Report", title: "The Power of 'Out' 2.0: LGBT in the Workplace", date: "Sep 2020", tag: "DEI Evolution", topic: "Organizational Culture & Trust", issues: "Bias, Courageous Conversations, Equity, Intersectionality, Representation", market: "U.S.", geography: ["United States"], identities: "LGBTQ", gated: true, series: null },
  { type: "Research Report", resourceType: "Research Report", title: "Innovation, Diversity and Market Growth", date: "Sep 2020", tag: "DEI Evolution", topic: "Organizational Culture & Trust", issues: "Innovation, Race", market: "U.S.", geography: ["United States"], identities: "Ethnicity", gated: true, series: null },
  { type: "Research Report", resourceType: "Research Report", title: "Vaulting the Color Bar", date: "Sep 2020", tag: "DEI Evolution", topic: "Organizational Culture & Trust", issues: "Bias, Race, Sponsorship", market: "U.S.", geography: ["United States"], identities: "Ethnicity", gated: true, series: null },
  { type: "Research Report", resourceType: "Research Report", title: "Winning the War for Talent in Emerging Markets", date: "Sep 2020", tag: "Talent Strategy", topic: "Talent & Performance", issues: "Advancement, Bias, Courageous Conversations, Talent Retention", market: "Brazil, China, India, Russia, UAE", geography: ["Brazil", "China", "India", "Russia", "UAE"], identities: "Women", gated: true, series: null },
  { type: "Research Report", resourceType: "Research Report", title: "Cracking the Code", date: "Sep 2020", tag: "DEI Evolution", topic: "Organizational Culture & Trust", issues: "Advancement, Bias, Race, Representation", market: "U.S.", geography: ["United States"], identities: "Ethnicity", gated: true, series: null },
  { type: "Research Report", resourceType: "Research Report", title: "On-Ramps and Up-Ramps India", date: "Sep 2020", tag: "Talent Strategy", topic: "Talent & Performance", issues: "Advancement, Intersectionality, Work Life Balance", market: "India", geography: ["India"], identities: "Women", gated: true, series: null },
];

const REPORT_DETAIL = {
  "The Convergent Leader": {
    subtitle: "How the best leaders in France, Germany, and the U.K. are combining strength and humanity — and what it takes to develop them.",
    description: "CTI's latest research examines what distinguishes high-performing leaders across France, Germany, and the United Kingdom. The most effective leaders are not the most forceful or the most empathetic — they are the most convergent: capable of holding both at once. Drawing on surveys of more than 2,500 employees and managers, this report identifies the four dimensions of convergent leadership, the organizational conditions that enable it, and the talent management failures that prevent it from scaling.",
    keyFindings: [
      "87% of employees in France, Germany, and the U.K. say they have experienced a leader who was either too directive or too deferential — rarely both in the right measure at the right moment.",
      "Convergent leaders — those who combine strategic clarity with interpersonal depth — are 3.4× more likely to retain high-performing direct reports across all three markets.",
      "Women leaders are disproportionately penalized for directiveness in France and Germany, while men are penalized for vulnerability in the U.K. — creating market-specific barriers to convergence.",
      "Only 22% of organizations surveyed have leadership development programs that develop both strategic and relational capability together.",
      "Gen Z employees across all three markets are more likely to demand convergent leadership from managers — and more likely to leave when they don't find it.",
      "Organizations that invest in convergent leadership development report 28% higher employee engagement and significantly lower voluntary attrition among high performers.",
    ],
    methodology: "Survey of 2,547 employees and 890 managers across France, Germany, and the United Kingdom. Conducted October–December 2025. Respondents drawn from organizations with 500+ employees across financial services, technology, professional services, and healthcare.",
    quote: {
      text: "The leaders who are most effective right now are not the ones who have mastered one mode of leadership. They're the ones who have stopped choosing.",
      source: "The Convergent Leader, Coqual Global Lab, 2026",
    },
    downloads: [
      { label: "Press Release", desc: "One-page media summary", gated: false },
      { label: "Executive Summary", desc: "6-page overview of key findings", gated: false },
      { label: "Full Report (PDF)", desc: "Complete 48-page research report", gated: false },
      { label: "Country Profiles", desc: "France, Germany, and U.K. data breakdowns", gated: false },
      { label: "Presentation Deck", desc: "Slides for internal briefings", gated: false },
    ],
    relatedForum: "The Futurist's Guide to Work Redesign · April 2027",
  },

  "The Neuroinclusion Imperative": {
    subtitle: "How performance systems misread neurodivergent contribution — and what organizations must do about it.",
    description: "Standard performance management was designed for a narrow band of cognitive styles. CTI's research reveals how feedback structures, advancement criteria, and meeting norms systematically disadvantage neurodivergent employees — not because of individual deficits, but because of institutional design failures. This report provides a framework for organizations to audit and redesign the systems that drive performance, recognition, and advancement.",
    keyFindings: [
      "71% of neurodivergent employees report that their performance has been negatively evaluated for behaviors directly attributable to their neurodivergence — not their output.",
      "Neurodivergent employees are significantly more likely to receive 'communication style' feedback than neurotypical peers at the same performance level.",
      "Organizations with neuroinclusive performance practices report 34% higher retention of neurodivergent talent and measurably higher innovation output from those teams.",
      "Only 18% of managers have received any training on how neurodivergence affects work style, communication, and contribution — despite 1 in 5 employees self-identifying as neurodivergent.",
      "The most common barrier to neuroinclusion is not resistance — it is the assumption that current systems are already neutral.",
      "Simple structural changes — written agendas, flexible participation formats, output-based evaluation — produce the largest gains and benefit all employees, not just neurodivergent ones.",
    ],
    methodology: "Mixed-methods study including surveys of 3,100 employees (560 self-identified as neurodivergent), 45 in-depth interviews, and analysis of performance review data from 12 partner organizations. Conducted 2024–2025.",
    quote: {
      text: "The performance review doesn't measure contribution. It measures legibility. And legibility is a design choice — one that most organizations have never consciously made.",
      source: "The Neuroinclusion Imperative, Coqual Global Lab, 2025",
    },
    downloads: [
      { label: "Press Release", desc: "One-page media summary", gated: false },
      { label: "Executive Summary", desc: "8-page overview of key findings", gated: false },
      { label: "Full Report (PDF)", desc: "Complete 52-page research report", gated: false },
      { label: "Manager's Guide", desc: "Practical tool for people managers", gated: false },
      { label: "Performance Audit Framework", desc: "Template for auditing your performance system", gated: false },
    ],
    relatedForum: "Work Style, Feedback, and Neuroinclusive Performance · October 2027",
  },

  "Challenging Norms": {
    subtitle: "A global study of how workplace bias intersects across race, gender, generation, and sexual orientation.",
    description: "Challenging Norms examines how bias operates differently across intersecting identities in eight major markets. The research surfaces the invisible tax that employees from underrepresented groups pay daily — and the business cost organizations absorb when they fail to design it out.",
    keyFindings: [
      "Employees from multiple underrepresented groups experience compounding bias — the effects are multiplicative, not additive.",
      "Sponsorship gaps are widest for employees who sit at the intersection of multiple marginalized identities.",
      "Pay gap analysis reveals that intersectional identity combinations predict salary more reliably than any single characteristic, after controlling for role and tenure.",
      "Managers underestimate the bias tax by an average of 60% compared to employee self-report.",
    ],
    methodology: "Survey of 12,000 employees across Australia, Brazil, Germany, India, Japan, South Africa, U.K., and U.S. Conducted 2022–2023.",
    quote: {
      text: "Bias is not experienced in categories. It is experienced in combination. Organizations that address it one dimension at a time will never close the gap.",
      source: "Challenging Norms, Coqual Global Lab, 2023",
    },
    downloads: [
      { label: "Press Release", desc: "One-page media summary", gated: false },
      { label: "Executive Summary", desc: "Key findings overview", gated: false },
      { label: "Full Report (PDF)", desc: "Complete research report", gated: false },
      { label: "Country Profiles", desc: "Market-specific findings", gated: false },
    ],
    relatedForum: "DEI Language After the Rollbacks · November 2027",
  },

  "The Sponsor Dividend": {
    subtitle: "What happens when sponsorship works — and the measurable return for organizations that invest in it.",
    description: "The Sponsor Dividend documents the career acceleration that sponsored employees experience compared to unsponsored peers with equivalent performance ratings — and quantifies the organizational return on sponsorship investment.",
    keyFindings: [
      "Sponsored employees are 23% more likely to be promoted within 18 months than unsponsored peers with equivalent performance ratings.",
      "Sponsorship accelerates advancement more for women and employees of color than for any other group.",
      "Most sponsorship in organizations is informal, invisible, and concentrated among employees who already have proximity to power.",
      "Organizations with formal sponsorship programs show measurably higher retention of high-potential talent across all demographics.",
    ],
    methodology: "Survey of 4,000 employees and 800 senior leaders across multiple U.S. industries, with longitudinal follow-up 18 months post-survey.",
    quote: {
      text: "Mentors give you feedback. Sponsors put their reputation on the line for you. The career gap between those two things is enormous.",
      source: "The Sponsor Dividend, Coqual Global Lab, 2020",
    },
    downloads: [
      { label: "Press Release", desc: "One-page media summary", gated: false },
      { label: "Executive Summary", desc: "Key findings overview", gated: false },
      { label: "Full Report (PDF)", desc: "Complete research report", gated: false },
    ],
    relatedForum: "Sponsorship Without Proximity · October 2027",
  },
};

const LUMINARIES = [
  {
    name: "Jennifer Brown",
    title: "Founding Luminary at the Global Lab",
    org: "CTI", topic: "Leadership", geography: ["Global"],
    tags: ["Leadership + Culture", "DEI Evolution"],
    provocation: "The leader you show at work is a design choice. Most people have never made it consciously.",
    problemAfterNext: "As identity becomes more visible and more contested, organizations will need leaders who can hold complexity without collapsing it — and most leadership development pipelines are not building that capacity.",
    blog: "Why Inclusive Leadership Is the Only Kind Left",
    podcast: "On Being Seen: Identity, Power, and the Workplace",
    book: "How to Be an Inclusive Leader (2nd ed.)",
  },
  {
    name: "Ernest Adams",
    title: "Founder & CEO",
    org: "Hustle with Heart", topic: "Talent & Performance", geography: ["Global"],
    tags: ["Talent Strategy", "Future of Work"],
    provocation: "Hustle culture is a poverty mindset with better marketing. Organizations that depend on it are one recession away from collapse.",
    problemAfterNext: "The next workforce crisis will not be a skills gap. It will be a meaning gap. Organizations will lose people not to competitors but to irrelevance.",
    blog: "The Hustle Trap: What Ambition Culture Is Costing Your Organization",
    podcast: "Purpose Over Productivity",
    book: null,
  },
  {
    name: "Trey Boynton",
    title: "Chief Diversity & People Officer",
    org: "Chief", topic: "Organizational Culture & Trust", geography: ["Global"],
    tags: ["DEI Evolution", "Leadership + Culture"],
    provocation: "DEI is not a program. It's an operating system. And most organizations are running a corrupted version.",
    problemAfterNext: "After the rollbacks, organizations that survive will be the ones that embedded equity into operational decisions — not just into HR programs. Most haven't started.",
    blog: "After the Rollback: What Real DEI Commitment Looks Like Now",
    podcast: "Rethinking the Chief Diversity Officer",
    book: null,
  },
  {
    name: "Tony Bynum, MBA MDM",
    title: "Assoc. Industry Professor & Director, ID Executive Academy",
    org: "Institute of Design (ID) at Illinois Tech", topic: "Future of Work", geography: ["United States"],
    tags: ["Workforce Design", "AI + Work"],
    provocation: "Design thinking was supposed to democratize innovation. Instead we've professionalized it into the hands of a few. That's the problem after next.",
    problemAfterNext: "AI is producing outputs faster than humans can evaluate them. The critical skill of the next decade is not generation — it's discernment. We are not building that.",
    blog: "Designing for Discernment in an AI-Saturated Workplace",
    podcast: "What Design Thinking Gets Wrong About Innovation",
    book: null,
  },
  {
    name: "Tomas Chamorro-Premuzic, Ph.D.",
    title: "Chief Science Officer",
    org: "Russell Reynolds Associates", topic: "Talent & Performance", geography: ["United States"],
    tags: ["Talent Strategy", "Organizational Performance"],
    provocation: "We promote people for what they've done and judge them for who they are. That mismatch is the root of most leadership failures.",
    problemAfterNext: "Psychometric data will soon tell organizations more about candidates than interviews ever could. The question is whether they'll have the courage to use it — or the wisdom to know its limits.",
    blog: "The Science of Bad Leadership: Why We Keep Getting It Wrong",
    podcast: "Personality, Performance, and the Illusion of Meritocracy",
    book: "I, Human: AI, Automation, and the Quest to Reclaim What Makes Us Unique",
  },
  {
    name: "Kate Devlin, Ph.D.",
    title: "Professor of AI & Society · Chair-Director, Digital Futures Institute",
    org: "King's College London", topic: "AI & Workforce", geography: ["United Kingdom"],
    tags: ["AI + Work", "Trust + Institutional Risk"],
    provocation: "We are building AI in the image of human bias and calling it intelligence. The question is not whether AI will be fair — it's whether we'll know when it isn't.",
    problemAfterNext: "The governance frameworks being built now will calcify into the regulatory regimes of 2035. Organizations that are not shaping those frameworks are accepting the version that gets built without them.",
    blog: "Who Is Accountable When the Algorithm Decides?",
    podcast: "AI, Ethics, and the Futures We're Building Without Realizing It",
    book: "Turned On: Science, Sex and Robots",
  },
  {
    name: "Rev. Mark Fowlder",
    title: "CEO",
    org: "Tanenbaum Center", topic: "Organizational Culture & Trust", geography: ["United States"],
    tags: ["Trust + Institutional Risk", "Leadership + Culture"],
    provocation: "Organizations have a spiritual problem they're calling a culture problem. The two require very different interventions.",
    problemAfterNext: "As religious and worldview diversity deepens in the workforce, organizations that have no framework for meaning — only for performance — will fail to retain the people who have one.",
    blog: "Beyond Culture: What Organizations Get Wrong About Belonging",
    podcast: "Faith, Work, and the Meaning Crisis Nobody Is Talking About",
    book: null,
  },
  {
    name: "Charlene Li",
    title: "Author, Futurist, Founder & CEO",
    org: "Quantum Networks Group", topic: "Leadership", geography: ["Global"],
    tags: ["Leadership + Culture", "Future of Work"],
    provocation: "The most dangerous thing a leader can do right now is remain relevant by staying comfortable.",
    problemAfterNext: "The leaders who will matter in 2030 are being formed by their decisions right now — in AI, in trust, in who they choose to hear. Most don't know they're being tested.",
    blog: "The Disruption Mindset: Why Some Leaders Thrive Through Change",
    podcast: "Radical Openness and the Future of Leadership",
    book: "The Disruption Mindset",
  },
  {
    name: "Lee Elliot Major OBE FAcSS",
    title: "Professor of Social Mobility",
    org: "University of Exeter", topic: "Talent & Performance", geography: ["United Kingdom"],
    tags: ["Talent Strategy", "DEI Evolution"],
    provocation: "Social mobility is not about moving people up the ladder. It's about changing who built the ladder and who decides where it goes.",
    problemAfterNext: "By 2033, demographic decline means organizations can no longer afford to discard talent. Social mobility will stop being a values question and become a survival question.",
    blog: "The Talent Math Doesn't Work Anymore: Social Mobility as Business Strategy",
    podcast: "Class, Mobility, and the Meritocracy Myth",
    book: "Social Mobility: And Its Enemies",
  },
  {
    name: "Hema Prapoo",
    title: "Worldwide Energy Industry Leader",
    org: "Microsoft", topic: "Future of Work", geography: ["United States"],
    tags: ["Future of Work", "AI + Work"],
    provocation: "Energy transition is a talent problem masquerading as a technology problem. We don't have enough people who can think in both languages.",
    problemAfterNext: "The intersection of AI and energy will produce the most consequential workforce decisions of the next decade — and most organizations are treating them as separate problems.",
    blog: "The Human Side of the Energy Transition",
    podcast: "Building the Workforce That Can Power the Future",
    book: null,
  },
  {
    name: "Jennifer D. Sciubba, Ph.D.",
    title: "President and CEO",
    org: "Population Reference Bureau", topic: "Future of Work", geography: ["United States"],
    tags: ["Future of Work", "Talent Strategy"],
    provocation: "Every talent strategy built on assumptions about population growth is already obsolete. The demographic math doesn't lie.",
    problemAfterNext: "By 2033, U.S. deaths will exceed births. The Asia-Pacific workforce begins permanent decline around 2035. Organizations planning 10-year talent pipelines are planning for a world that will not exist.",
    blog: "The Demographic Cliff: What It Means for Every Talent Strategy",
    podcast: "8 Billion and Counting: Population, Power, and the Future of Work",
    book: "8 Billion and Counting",
  },
  {
    name: "Anna Tavis, Ph.D.",
    title: "Clinical Professor, Human Capital Management",
    org: "New York University", topic: "Talent & Performance", geography: ["United States"],
    tags: ["Talent Strategy", "Organizational Performance"],
    provocation: "Human capital management was designed for a world of stable jobs and linear careers. We are trying to use 20th-century tools on 21st-century problems.",
    problemAfterNext: "The performance management systems most organizations use were built for industrial-era assumptions. AI is exposing how badly they misfit the work people are actually doing.",
    blog: "The Performance Review Is Not Broken. It Was Never Right.",
    podcast: "Reimagining HR for the Age of AI",
    book: "Humans at Work",
  },
  {
    name: "Alison Taylor",
    title: "Clinical Associate Professor of Business & Society",
    org: "New York University", topic: "Organizational Culture & Trust", geography: ["United States"],
    tags: ["Trust + Institutional Risk", "Organizational Performance"],
    provocation: "Corporate ethics has been outsourced to compliance departments. That's not ethics — that's risk management in a suit.",
    problemAfterNext: "The organizations that will survive the next decade of institutional distrust are not the ones with the best compliance programs. They're the ones that made genuine commitments before the crisis arrived.",
    blog: "Why Corporate Ethics Keeps Failing (and What Would Actually Fix It)",
    podcast: "Higher Ground: Business Ethics in an Age of Institutional Collapse",
    book: "Higher Ground: How Business Can Do the Right Thing in a Turbulent World",
  },
];

const LUMINARY_PODCAST_EPISODES = [
  { luminary: "Jennifer Brown", episode: "On Being Seen: Identity, Power, and the Workplace", duration: "48 min" },
  { luminary: "Tomas Chamorro-Premuzic", episode: "Personality, Performance, and the Illusion of Meritocracy", duration: "54 min" },
  { luminary: "Charlene Li", episode: "Radical Openness and the Future of Leadership", duration: "41 min" },
  { luminary: "Alison Taylor", episode: "Higher Ground: Business Ethics in an Age of Institutional Collapse", duration: "52 min" },
  { luminary: "Jennifer D. Sciubba", episode: "8 Billion and Counting: Population, Power, and the Future of Work", duration: "46 min" },
  { luminary: "Kate Devlin", episode: "AI, Ethics, and the Futures We're Building Without Realizing It", duration: "39 min" },
];

const MEMBER_PAGES = [
  "dashboard", "forum-calendar", "session-before", "session-after",
  "event-detail-member", "past-event-detail",
  "consequential-member", "post-member", "playbooks", "playbook-detail",
  "coalition", "luminary-archive", "luminary-profile", "advisory-member",
  "ctilearning", "member-directory", "my-membership",
  "research", "luminary-exchange-member", "summit-member",
];

// Real published Summit session videos (source: Summit Videos Archive,
// WordPress published-pages export). topic/geography/resourceType are
// added metadata for the taxonomy/search system, not in the source doc.
const SUMMIT_VIDEOS = [
  { title: "Carrying the Torch: A Fireside Chat Between Phylicia Rashad & Soledad O’Brien", summit: "Summit 2024", published: "Nov 19, 2024", topic: "Leadership", geography: ["Global"], resourceType: "Video" },
  { title: "EPIC! Players Opening Performance", summit: "Summit 2024", published: "Nov 19, 2024", topic: "Leadership", geography: ["Global"], resourceType: "Video" },
  { title: "History & Stories to Light Our Way", summit: "Summit 2025", published: "Dec 2, 2025", topic: "Organizational Culture & Trust", geography: ["Global"], resourceType: "Video" },
  { title: "Inclusion 2.0", summit: "Summit 2025", published: "Dec 2, 2025", topic: "Organizational Culture & Trust", geography: ["Global"], resourceType: "Video" },
  { title: "Is AI Cheating? Women, Work, & the Next Wave of Leadership", summit: "Summit 2025", published: "Dec 10, 2025", topic: "AI & Workforce", geography: ["Global"], resourceType: "Video" },
  { title: "LGBTQ+ Research Report Preview and Conversation", summit: "Summit 2024", published: "Nov 19, 2024", topic: "Organizational Culture & Trust", geography: ["Global"], resourceType: "Video" },
  { title: "Navigating Risk with Purpose: A Conversation Between CDOs and Legal Experts", summit: "Summit 2024", published: "Nov 20, 2024", topic: "Organizational Culture & Trust", geography: ["Global"], resourceType: "Video" },
  { title: "Rethinking Assumptions in an Age of Demographic Change", summit: "Summit 2025", published: "Dec 2, 2025", topic: "Future of Work", geography: ["Global"], resourceType: "Video" },
  { title: "Social Mobility: A Roadmap to Inclusion & Innovation", summit: "Summit 2024", published: "Nov 21, 2024", topic: "Career Mobility & Opportunity", geography: ["Global"], resourceType: "Video" },
  { title: "The Beauty of Belonging: A Fireside Chat with Marilu Marshall", summit: "Summit 2024", published: "Nov 21, 2024", topic: "Organizational Culture & Trust", geography: ["Global"], resourceType: "Video" },
  { title: "The DEIB Paradigm Shift: Traction for the Future", summit: "Summit 2024", published: "Nov 19, 2024", topic: "Organizational Culture & Trust", geography: ["Global"], resourceType: "Video" },
  { title: "The Leadership We Need Now", summit: "Summit 2025", published: "Dec 2, 2025", topic: "Leadership", geography: ["Global"], resourceType: "Video" },
  { title: "The Power and Impact of Sponsorship in Corporate America", summit: "Summit 2024", published: "Nov 19, 2024", topic: "Career Mobility & Opportunity", geography: ["Global"], resourceType: "Video" },
  { title: "The Power of Possible: Negotiating Clarity in Uncertain Times", summit: "Summit 2025", published: "Dec 2, 2025", topic: "Leadership", geography: ["Global"], resourceType: "Video" },
  { title: "We are the Leaders We Have Been Looking For: A Fireside Chat with Eddie S. Glaude", summit: "Summit 2024", published: "Nov 19, 2024", topic: "Leadership", geography: ["Global"], resourceType: "Video" },
  { title: "What Breaks Leaders – and What Saves Them", summit: "Summit 2025", published: "Dec 2, 2025", topic: "Leadership", geography: ["Global"], resourceType: "Video" },
];

// Real Summit 2026 sponsorship tiers (source: Sponsorship Prospectus content).
const SUMMIT_SPONSOR_LEVELS = [
  {
    level: "Presenting Sponsor", usd: "$50,000", gbp: "£37,500",
    audience: "Lead supporter of Coqual Summit 2026. For companies that want the strongest visibility across the full Summit experience.",
    supports: "The full in-person and virtual Summit experience",
    benefits: [
      "Top-level recognition across Summit materials",
      "Reserved seats for senior executives",
      "Recognition from the main stage",
      "Participation in the sponsor planning conversation",
      "Access to the pre-Summit Luminary Table",
      "Early access to the Summit Insights Brief",
      "Private post-Summit readout for internal leaders",
      "Opportunity to include global colleagues or clients in virtual programming",
    ],
  },
  {
    level: "General Session Sponsor", usd: "$25,000", gbp: "£18,750",
    audience: "For companies that want visibility around one of the central conversations of the day.",
    supports: "A keynote, panel, interview, or main-stage dialogue with senior leaders, luminaries, or issue experts",
    benefits: [
      "Recognition connected to the session",
      "Reserved seats for senior leaders",
      "Optional executive introduction or framing moment, where appropriate",
      "Session takeaways included in the post-Summit readout",
      "Opportunity to share relevant takeaways with global or UK-based stakeholders after the Summit",
    ],
  },
  {
    level: "Working Session Sponsor", usd: "$15,000", gbp: "£11,250",
    audience: "For companies that want more focused engagement with senior leaders.",
    supports: "A facilitated breakout or peer working session where leaders work through a practical question",
    benefits: [
      "Recognition tied to the session",
      "Reserved seats in the session",
      "Input into the working question",
      "Captured takeaways from the conversation",
      "Opportunity to nominate a sponsor executive participant, where appropriate",
    ],
  },
  {
    level: "Braindate Sponsor", usd: "$15,000", gbp: "£11,250",
    audience: "For companies that want to help hundreds of leaders connect through purposeful small-group networking across markets.",
    supports: "The Braindate experience for in-person and virtual participants",
    benefits: [
      "Recognition as the Braindate Sponsor",
      "Visibility across the networking and virtual experience",
      "Input into Braindate prompt categories",
      "Seats for global colleagues, clients, or partners",
      "Summary of common topics and questions from Braindate conversations",
      "Opportunity to support a UK-facing follow-up discussion or insight-sharing moment",
    ],
  },
  {
    level: "Luminary Exchange Sponsor", usd: "$15,000", gbp: "£11,250",
    audience: "For companies that want a closer role in shaping the ideas and questions explored at Summit.",
    supports: "A curated pre-Summit conversation with Coqual leaders, select luminaries, and sponsor participants",
    benefits: [
      "Seat at the Luminary Table",
      "Input into one question or theme",
      "Reserved Summit seats",
      "Recognition connected to the Luminary Table",
      "Post-Summit takeaways connected to the discussion",
    ],
  },
  {
    level: "Reception or Connection Sponsor", usd: "$10,000", gbp: "£7,500",
    audience: "For companies that want to support the human connection that makes the Summit valuable.",
    supports: "Breakfast, lunch, reception, curated networking, Big Talk, or other relationship-building moments",
    benefits: [
      "Recognition connected to the experience",
      "Reserved seats",
      "Optional welcome moment, where appropriate",
      "Visibility in event materials and onsite signage",
    ],
  },
  {
    level: "Summit Insights Sponsor", usd: "$5,000", gbp: "£3,750",
    audience: "For companies that want the Summit to create something useful after the Summit.",
    supports: "A concise Coqual-written executive brief capturing what leaders discussed, questioned, and prioritized",
    benefits: [
      "Recognition on the brief",
      "Early access to the brief",
      "Private readout for internal leaders",
      "Reserved Summit seats",
      "Opportunity to suggest one question for Coqual to listen for across the day",
    ],
  },
];
